### PR TITLE
Fixed inconsistencies with NoClip V1 and V2

### PR DESCRIPTION
**Pull request by SimpleSandman**
Fixed the invisibility issue when using NoClip from the UI by rewriting how both CLI and UI utilize this feature.
Reworked underlying code for NoClip to allow better accessibility and readibility.
Also ensured invincibility is used for both versions of NoClip.

Also replaced old server-side `Logger` code with what's in VORP-Inventory to allow configs from `server.cfg`. This will allow us to build out any logging in the same way.

Here's the build file for testing and deployment:
[build.zip](https://github.com/VORPCORE/VORP-AdminMenu/files/8419860/build.zip)

### CODE REVIEW

**Comment by outsider31000** [comment]
This will be reviewed . Thanks bud

**Comment by Local9** [comment]
Code looks fine, I've not dealt with this resource so I don't know what to compare between the two types of NoClip, but I would recommend changing the V1 to be a legacy system (or removing it) and that `noclip` commands all use the new version.

Logger file is fine for on the fly changing of the convar and as it is now, is fine to use. Future usage will be done using the CFX native `GetResourceMetadata` and will help keep the `.cfg` files cleaner with keeping configuration inside the resource fxmanifest. An example can be found here: https://github.com/Local9/VORP-Core/blob/vorp-core-refactor/Vorp.Shared/Diagnostics/Logger.cs

**Comment by outsider31000** [comment]
yeah, agree there's no need to have 2 options for noclip.

**Comment by SimpleSandman** [comment]
Sounds good to me. I'll get to work on removing noclip v1

**Comment by outsider31000** [comment]
alright, I'll merge this one for now. thanks to yall

**Pull request merged**
